import fs from 'node:fs';
import path from 'node:path';

/** Directory where OpenClaw stores its configuration */
const OPENCLAW_HOME = path.join(process.env.HOME || '', '.openclaw');

/** Path to the OpenClaw config file generated by the wizard */
const OPENCLAW_CONFIG = path.join(OPENCLAW_HOME, 'openclaw.json');

/**
 * Detect whether this is a first run by checking if the OpenClaw config file exists.
 * Returns true when no config file exists (wizard should auto-launch),
 * false when it does (wizard should be skipped).
 */
export function isFirstRun(): boolean {
  return !fs.existsSync(OPENCLAW_CONFIG);
}
